version: 2
jobs :
  build:
    working_directory: ~/tmp
    docker:
        - image: circleci/node:8
    steps:
        - setup_remote_docker
        - checkout
        - run: docker build -t platzi .
        - run: docker run platzi npm test
        - run: sh deployments/qa.sh
        - run: sh deployments/prod.sh

   deploy-qa:
    docker:
      # specify the version you desire here
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: deploy to qa
          command:  sh deployments/qa.sh
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

    deploy-prod:
    docker:
      # specify the version you desire here
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: deploy to prod
          command: sh deployments/prod.sh
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version:2
  central_flow:
      jobs:
        - build
        - deploy-qa:
            requires:
              - build
            filters:
              branches:
                only: /feature_.*/
        - deploy-prod:
            requires:
              - build
            filters:
              branches:
                only: master
